/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_today_im_IMMuxer */

#ifndef _Included_com_today_im_IMMuxer
#define _Included_com_today_im_IMMuxer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_today_im_IMMuxer
 * Method:    initWithSampleRate
 * Signature: (II)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_today_im_IMMuxer_initWithSampleRate
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_today_im_IMMuxer
 * Method:    stopCalled
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_today_im_IMMuxer_stopCalled
  (JNIEnv *, jobject);

/*
 * Class:     com_today_im_IMMuxer
 * Method:    startPublishWithUrl
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_today_im_IMMuxer_startPublishWithUrl
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_today_im_IMMuxer
 * Method:    stopPublish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_today_im_IMMuxer_stopPublish
  (JNIEnv *, jobject);

/*
 * Class:     com_today_im_IMMuxer
 * Method:    write
 * Signature: ([BIII)I
 */
JNIEXPORT jint JNICALL Java_com_today_im_IMMuxer_write
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint);

/*
 * Class:     com_today_im_IMMuxer
 * Method:    playWithUrl
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_today_im_IMMuxer_playWithUrl
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_today_im_IMMuxer
 * Method:    replayWithUrl
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_today_im_IMMuxer_replayWithUrl
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_today_im_IMMuxer
 * Method:    stopPull
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_today_im_IMMuxer_stopPull
  (JNIEnv *, jobject);

/*
 * Class:     com_today_im_IMMuxer
 * Method:    startPlay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_today_im_IMMuxer_startPlay
  (JNIEnv *, jobject);

/*
 * Class:     com_today_im_IMMuxer
 * Method:    stopPlay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_today_im_IMMuxer_stopPlay
  (JNIEnv *, jobject);

/*
 * Class:     com_today_im_IMMuxer
 * Method:    read
 * Signature: ()Lcom/today/im/PacketInfo;
 */
JNIEXPORT jobject JNICALL Java_com_today_im_IMMuxer_read
  (JNIEnv *, jobject);

/*
 * Class:     com_today_im_IMMuxer
 * Method:    isConnected
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_today_im_IMMuxer_isConnected
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
