/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_today_im_IMMuxer */

#ifndef _Included_com_today_im_IMMuxer
#define _Included_com_today_im_IMMuxer
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL
Java_com_today_im_IMMuxer_getSalt(JNIEnv *env, jobject instance) {
    char salt[] = "6291D258227040D0A53203C1C5225275";
    const char *salt1 = (char *) malloc(strlen(salt));
    strcat(salt1, salt);

    jstring result = (*env)->NewStringUTF(env, salt1);

    free(salt1);

    return result;
}

JNIEXPORT jint JNICALL
Java_com_today_im_IMMuxer_publish(JNIEnv *, jobject, jstring, jint,
                                  jstring, jstring, jstring, jstring);

JNIEXPORT void JNICALL Java_com_today_im_IMMuxer_stopPublish
        (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_today_im_IMMuxer_isPublishConnected
        (JNIEnv *, jobject);

JNIEXPORT jint JNICALL
Java_com_today_im_IMMuxer_pull(JNIEnv *, jobject, jstring, jint,
                               jstring, jstring, jstring, jstring);

JNIEXPORT void JNICALL Java_com_today_im_IMMuxer_stopPull
        (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_today_im_IMMuxer_isPullConnected
        (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_today_im_IMMuxer_write
        (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jstring);

JNIEXPORT jobject JNICALL Java_com_today_im_IMMuxer_read
        (JNIEnv *, jobject, jstring);


#ifdef __cplusplus
}
#endif
#endif
