/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_today_im_IMMuxer */

#ifndef _Included_com_today_im_IMMuxer
#define _Included_com_today_im_IMMuxer
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL
Java_com_today_im_IMMuxer_getSalt(JNIEnv *env, jobject instance) {
    char salt[] = "6291D258227040D0A53203C1C5225275";
    const char *salt1 = (char *) malloc(strlen(salt));
    strcat(salt1, salt);

    jstring result = (*env)->NewStringUTF(env, salt1);

    free(salt1);

    return result;
}

JNIEXPORT jint JNICALL
Java_com_today_im_IMMuxer_publish(JNIEnv *, jobject, jstring, jint,
                                  jstring, jstring, jstring, jstring);

JNIEXPORT jint JNICALL
Java_com_today_im_IMMuxer_pull(JNIEnv *, jobject, jstring, jint,
                               jstring, jstring, jstring, jstring);


JNIEXPORT jint JNICALL
Java_com_today_im_IMMuxer_publish1(JNIEnv *, jobject);


JNIEXPORT jint JNICALL
Java_com_today_im_IMMuxer_pullInit(JNIEnv *, jobject, jstring, jstring,
                                   jstring, jstring, jstring, jstring);


JNIEXPORT jint JNICALL
Java_com_today_im_IMMuxer_pull1(JNIEnv *, jobject);

/*
 * Class:     com_today_im_IMMuxer
 * Method:    initWithSampleRate
 * Signature: (II)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_today_im_IMMuxer_initWithSampleRate
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_today_im_IMMuxer
 * Method:    stopCalled
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_today_im_IMMuxer_stopCalled
        (JNIEnv *, jobject);

/*
 * Class:     com_today_im_IMMuxer
 * Method:    publishWithUrl
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_today_im_IMMuxer_publishWithUrl
        (JNIEnv *, jobject, jstring);

/*
 * Class:     com_today_im_IMMuxer
 * Method:    stopPublish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_today_im_IMMuxer_stopPublish
        (JNIEnv *, jobject);


/*
 * Class:     com_today_im_IMMuxer
 * Method:    isConnected
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_today_im_IMMuxer_isPublishConnected
        (JNIEnv *, jobject);

/*
 * Class:     com_today_im_IMMuxer
 * Method:    write
 * Signature: ([BIII)I
 */
JNIEXPORT jint JNICALL Java_com_today_im_IMMuxer_write
        (JNIEnv *, jobject, jbyteArray, jint, jint, jint);

/*
 * Class:     com_today_im_IMMuxer
 * Method:    pullWithUrl
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_com_today_im_IMMuxer_pullWithUrl
        (JNIEnv *, jobject, jstring);

/*
 * Class:     com_today_im_IMMuxer
 * Method:    replayWithUrl
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_today_im_IMMuxer_replayWithUrl
        (JNIEnv *, jobject, jstring);

/*
 * Class:     com_today_im_IMMuxer
 * Method:    stopPull
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_today_im_IMMuxer_stopPull
        (JNIEnv *, jobject);

/*
 * Class:     com_today_im_IMMuxer
 * Method:    startPlay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_today_im_IMMuxer_startPlay
        (JNIEnv *, jobject);

/*
 * Class:     com_today_im_IMMuxer
 * Method:    isConnected
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_today_im_IMMuxer_isPullConnected
        (JNIEnv *, jobject);


/*
 * Class:     com_today_im_IMMuxer
 * Method:    stopPull
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_today_im_IMMuxer_stopPlay
        (JNIEnv *, jobject);

/*
 * Class:     com_today_im_IMMuxer
 * Method:    read
 * Signature: ()Lcom/today/im/PacketInfo;
 */
JNIEXPORT jobject JNICALL Java_com_today_im_IMMuxer_read
        (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
